package net.saisimon.leetcode;

/**
 * 389. Find the Difference
 * 	Given two strings s and t which consist of only lowercase letters.
 * 	String t is generated by random shuffling string s and then add one more letter at a random position.
 * 	Find the letter that was added in t.
 * 	Example:
 * 	Input:
 *	s = "abcd"
 *	t = "abcde"
 *
 *	Output:
 *	e
 *
 *	Explanation:
 *	'e' is the letter that was added.
 * 
 * @author Saisimon
 *
 */
public class FindDifference {
	public char findTheDifference(String s, String t) {
        int[] sarr = new int[26];
        int[] tarr = new int[26];
        for (int i = 0; i < s.length(); i++) {
        	sarr[s.charAt(i) - 'a']++;
        }
        for (int i = 0; i < t.length(); i++) {
        	tarr[t.charAt(i) - 'a']++;
        }
        // 比较两个数组的不同
        for (int i = 0; i < tarr.length; i++) {
			if (sarr[i] != tarr[i]) {
				return (char)(i + 'a');
			}
		}
        return ' ';
    }
	
}
